version: '3.0'

services:
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www/app
    container_name: nginx
    restart: always
    ports:
      - "8881:81"
    networks:
      - myProject

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www/app
    container_name: php-fpm
    restart: always
    depends_on:
      - mysql
    networks:
      - myProject

  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - myProject

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin

    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8090:80"
    networks:
      - myProject

  mailer:
    image: schickling/mailcatcher
    container_name: mailer
    ports:
      - "1025"
      - "1080:1080"
    networks:
      - myProject

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - myProject

  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
    networks:
      - myProject

  kibana:
    image: kibana:8.10.2
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
    networks:
      - myProject

networks:
  myProject:
    driver: bridge

volumes:
  dbdata: