version: '3.0'

services:
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www/app
    container_name: d_nginx
    restart: always
    ports:
      - "8881:81"
    networks:
      - myProject

  php-fpm:
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www/app
    container_name: d_php-fpm
    restart: always
    depends_on:
      - mysql
    networks:
      - myProject

  mysql:
    image: mysql
    restart: always
    container_name: d_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - myProject

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: d_phpmyadmin

    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8090:80"
    networks:
      - myProject

  mailer:
    image: schickling/mailcatcher
    container_name: d_mailer
    ports:
      - "1025"
      - "1080:1080"
    networks:
      - myProject

  redis:
    image: redis
    container_name: d_redis
    ports:
      - '6379:6379'
    networks:
      - myProject

networks:
  myProject:
    driver: bridge

volumes:
  dbdata: